### ISSUE TITLE
Frontespizio isn't updating

### ISSUE THREAD

**Issue by mega2799** [NiccoMlt/Unibo-Tesi-Template#26]
Hi, thank you a lot for this template, it's really useful but i've got a problem...
I'm trying to edit the frontespizio but i can't, i tried on visual studio and i edited it once and now i can't anymore ([my repository](https://github.com/mega2799/Tesi-Curriculare-Santoro) if you want to try build it with the recipe: mega, arara isn't working with minted) and i tried to upload the file on overleaf but i get the template frontespizio and not the one i wrote (https://www.overleaf.com/read/kfdhkrrkftyz)
(The file tesi-frn.pdf is genereted correctly but seems that is not linked with tesi.pdf)
I have no clue why this isn't working anymore
Waiting for a response, good Evening

**Comment by NiccoMlt** [comment]
Hi Matteo, I would like to help you, but it's difficult for me to diagnose the problem without some log or any detail about your setup!

Ignoring Overleaf for now, what OS and LaTeX distribution are you working on? Also, LaTeX is logging any errors about `frontespizio` package, or any other package?

Also, the phrase

> arara isn't working with minted

sounds very strange to me, it may be a problem with the environment setup, it should work just fine. The recipe you wrote uses `lualatex` directly, which works just fine with the main document structure, but it doesn't invoke `frontespizio` command to refresh the frontspice, nor it invokes `biber` for the bibliography generation

Finally, opening the Overleaf link everything looks good to me:
![screenshot](https://user-images.githubusercontent.com/18643366/187082927-57367128-74c2-4cb1-9bcb-30bc377167b0.png)

Why you say that you that you get the template and not the one you wrote? What's missing?

**Comment by NiccoMlt** [comment]
Is your problem resolved? Can I close this issue?

**Comment by NiccoMlt** [comment]
I'm closing this issue, feel free to reopen it if needed
